<?php
/**
 * @file
 *
 * Hooks and functions for iowa_counties module.
 * Vocabulary creation and population done in iowa_counties.install.
 */


/**
 * Implements hook_views_api().
 */
function iowa_counties_views_api() {
  return array (
    'api' => 3.0,
    'path' => drupal_get_path('module', 'iowa_counties'),
  );
}

/**
 * Implements hook_views_pre_render().
 */
function iowa_counties_views_pre_render(&$view) {
  // Add some default CSS to style the iowa_counties views.
  if ($view->name == 'iowa_counties') {
    drupal_add_css(drupal_get_path('module', 'iowa_counties') . '/css/views.css');
  }
}
